Feat/int 717 automatically detect git remote path in vscode
intuita-inc/intuita-vscode-extension pull request #214
Opened 2023-04-04 13:51 UTC by henoktsegayetoptal

2023-04-05 10:10 UTC, grzpab requested changes
See inline comments

2023-04-05 10:10 UTC, grzpab commented on src/configuration.ts
> +					console.error('error', error);
You can just write `console.error(error)`

2023-04-05 10:10 UTC, grzpab commented on src/configuration.ts
> +					if (repositoryPath) {
I'd revert the logic here (so return if `!repositoryPath`)

2023-04-05 10:10 UTC, grzpab commented on src/configuration.ts
> +		new Promise(async (resolve, reject) => {
actually I think it's a serious antipattern: https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it/23803744#23803744

I think you can make it an async function and create the promise within it when needed.

2023-04-05 10:10 UTC, grzpab commented on src/configuration.ts
> +			const gitExtension = vscode.extensions.getExtension(
can it throw?

2023-04-05 15:15 UTC, henoktsegayetoptal commented on src/configuration.ts
> +			const gitExtension = vscode.extensions.getExtension(
it can reject , not throw

2023-04-06 08:30 UTC, grzpab requested changes
See inline comments

2023-04-06 08:31 UTC, henoktsegayetoptal commented on src/configuration.ts
> +					);
unfortunately `activate()` doesn't have a catch

2023-04-06 09:54 UTC, grzpab commented on src/types/git.d.ts
> + *  Licensed under the MIT License. See License.txt in the project root for license information.
did @DmytroHryshyn add the same file already?

2023-04-06 11:49 UTC, grzpab approved these changes

2023-04-06 12:40 UTC, merged